[mcp_servers.playwright]
args = [
    "@playwright/mcp@0.0.75",
    "--headless",
    "--isolated",
]
command = "npx"

[mcp_servers.playwright.tools.browser_resize]
approval_mode = "approve"

[mcp_servers.playwright.tools.browser_navigate]
approval_mode = "approve"
